### ISSUE TITLE
 Jupyter notebook should be uploaded to the Code section of your repository.

### ISSUE THREAD

**Issue by luisortizuriarte** [jwill96/Clim680#2]
Jupyter notebook should be uploaded to the Code section of your repository. See github's documentation below:

https://docs.github.com/en/repositories/working-with-files/managing-files/adding-a-file-to-a-repository

**Comment by jwill96** [comment]
I uploaded the Jupyter notebook to the Code section of my repository.

**Comment by luisortizuriarte** [comment]
This is done, so closing issue.
